# -*- coding: utf-8 -*-
"""Submission 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ktPRvyA25yqODhUrrqdkjjIukHqQWzD

# Membuat Model NLP dengan TensorFlow

Dataset dari kaggle : [Spam Text Message Classification](https://www.kaggle.com/team-ai/spam-text-message-classification)
"""

import pandas as pd

df = pd.read_csv('/content/SPAM text message 20170820 - Data.csv')
df.head()

Category = pd.get_dummies(df.Category)
df_baru = pd.concat([df, Category], axis=1)
df_baru = df_baru.drop(columns='Category')
df_baru

from sklearn.model_selection import train_test_split

pesan = df_baru['Message'].values
label = df_baru[['spam']].values


pesan_latih, pesan_test, label_latih, label_test = train_test_split(pesan, label, test_size=0.2)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words=5000, oov_token='x')
tokenizer.fit_on_texts(pesan_latih)
tokenizer.fit_on_texts(pesan_test)

sekuens_latih = tokenizer.texts_to_sequences(pesan_latih)
sekuens_test = tokenizer.texts_to_sequences(pesan_test)

padded_latih = pad_sequences(sekuens_latih)
padded_test = pad_sequences(sekuens_test)

print(sekuens_latih)
print(sekuens_test)

import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=5000, output_dim=16),
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(128, activation='relu'),
    # tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid'),
])

model.compile(
    loss='binary_crossentropy',
    optimizer='adam',
    metrics=['accuracy']
)

num_epochs = 8
history = model.fit(padded_latih,
                    label_latih,
                    epochs=num_epochs,
                    validation_data=(padded_test, label_test),
                    verbose=2)